# Generated by Django 6.0.6 on 2026-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(choices=[('bruteforce', 'Brute Force'), ('xss', 'Cross-Site Scripting'), ('csrf', 'CSRF'), ('sqli', 'SQL Injection')], max_length=50)),
                ('event_type', models.CharField(help_text="e.g. 'login_attempt', 'lockout_triggered', 'payload_submitted'", max_length=50)),
                ('security_mode', models.CharField(help_text="'vulnerable' or 'hardened' - which mode was active when this happened", max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('success', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lab_name', 'created_at'], name='core_labeve_lab_nam_df7b5d_idx'), models.Index(fields=['ip_address'], name='core_labeve_ip_addr_b95a8f_idx')],
            },
        ),
    ]
